@startuml AplicacaoCodigo

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class Documento {
    - String Nome
    - String Descricao
    - Date publishDate
    - Boolean isAvailable

+ getNome() : String
+ getDescricao() : String
+ getPublishDate() : Date
+ checkAvailabity() : Boolean
}

@enduml