@startuml BibliotecaContext
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(usuario, "Usuário", "Usuario que interage com o sistema")
System(sistemaGestao, "Sistema de Gestão de Biblioteca", "Sistema que gerencia o catálogo de livros")
System_Ext(servicoPagamento, "Serviço de Pagamento", "Serviço externo que realiza o pagamento")
System_Ext(servicoNotificacao, "Serviço de Notificação", "Serviço externo que envia notificações")

Rel(usuario, sistemaGestao, "Usa")
Rel(sistemaGestao, servicoPagamento, "Processa pagamentos")
Rel(sistemaGestao, servicoNotificacao, "Envia notificações")

@enduml