@startuml AplicacaoContext
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(usuario, "Usuário", "Usuario que utiliza a aplicação")
System(sistemaProcessos, "Sistema de Gestão de Processos", "Sistema que gerencia os processos da empresa")
System_Ext(servicoValidacao, "Serviço de Validação do Processo", "Serviço externo que valida o processo")

Rel(usuario, sistemaProcessos, "Usa")
Rel(sistemaProcessos, servicoValidacao, "Valida Processo")

@enduml