@startuml
' !define RECTANGLE_COLOR #FFCC00
' !define Usuario #FF9900
left to right direction

actor Usuario
actor Administrador

rectangle "Sistema de Gestão" {
    Usuario -- (Realizar Login)
    Usuario -- (Visualizar Dados)
    Usuario -- (Atualizar Perfil)
    Administrador -- (Gerenciar Usuários)
    Administrador -- (Visualizar Relatórios)
    (Gerenciar Usuários) .> (Realizar Login) : <<include>>
}

@enduml