@startuml AplicacaoCodigo

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

class Documento {
    - String Nome
    - String Descricao
    - Date inclusaoData
    - Boolean isDisponivel

+ getNome() : String
+ getDescricao() : String
+ getDataInclusao() : Date
+ checkDisponivel() : Boolean
}

@enduml